import{useEffect,useMemo,useState}from'react';import{Activity,Archive,ArrowRight,BarChart3,Bot,Check,ChevronRight,Database,FileText,Gauge,Globe2,Layers3,LockKeyhole,LogOut,Network,Play,RefreshCw,Search,Settings,ShieldCheck,Sparkles,TriangleAlert,Wrench}from'lucide-react';import{api}from'./api';

type View='dashboard'|'agents'|'capabilities'|'campaigns'|'create'|'run'|'assets'|'settings';
type Agent={id:string;name:string;role:string;version:string;status:string;skills:string[];tools:string[];mcp_servers:string[];model_policy:string};
type Run={run_id:string;status:string;campaign:Record<string,any>;runtime_mode:string;model_id:string;updated_at:string};
type Stage={stage_id:string;name:string;status:string;version:number;sequence:number;agent_ids:string[];artifact_kinds:string[]};
const statusCN:Record<string,string>={locked:'已锁定',ready:'就绪',running:'执行中',pending_review:'待审核',approved:'已通过',rejected:'已驳回',revision_required:'需修改',failed:'失败',skipped:'已跳过',waiting_review:'待审批',optimized:'已完成',human_handoff:'人工接管'};
const nav=[['dashboard','运营总览',Gauge],['agents','Agent 能力中心',Bot],['capabilities','Skill / Tool / MCP',Wrench],['campaigns','Campaign 运行中心',Layers3],['assets','资产中心',Archive],['settings','平台设置',Settings]] as const;

function Badge({value}:{value:string}){return <span className={`badge s-${value}`}>{statusCN[value]||value}</span>}
function Empty({title,body}:{title:string;body:string}){return <div className="empty"><Sparkles/><h3>{title}</h3><p>{body}</p></div>}

export default function App(){
 const[authenticated,setAuthenticated]=useState<boolean|null>(null),[view,setView]=useState<View>('dashboard'),[runtime,setRuntime]=useState<any>(),[agents,setAgents]=useState<Agent[]>([]),[runs,setRuns]=useState<Run[]>([]),[selected,setSelected]=useState<Run|null>(null),[stages,setStages]=useState<Stage[]>([]),[bundle,setBundle]=useState<any>({}),[busy,setBusy]=useState(true),[error,setError]=useState('');
 const load=async()=>{setBusy(true);setError('');try{const[r,a,c]=await Promise.all([api('/api/runtime'),api('/api/agents'),api('/api/runs')]);setRuntime(r);setAgents(a.items||[]);setRuns(c.items||[])}catch(e:any){if(e.status===401)setAuthenticated(false);else setError(e.message)}finally{setBusy(false)}};
 useEffect(()=>{api('/api/auth/session').then((s:any)=>{setAuthenticated(Boolean(s.authenticated));if(s.authenticated)load()}).catch(()=>setAuthenticated(false))},[]);
 const openRun=async(run:Run)=>{setSelected(run);setView('run');setBusy(true);try{const[s,g,e,c,a,t,m]=await Promise.all([api(`/api/runs/${run.run_id}/stages`),api(`/api/runs/${run.run_id}/graph`),api(`/api/runs/${run.run_id}/evidence`),api(`/api/runs/${run.run_id}/conflicts`),api(`/api/runs/${run.run_id}/assets`),api(`/api/runs/${run.run_id}/artifacts`),api(`/api/runs/${run.run_id}/metrics`)]);setStages(s.items||[]);setBundle({graph:g,evidence:e.items||[],conflicts:c.items||[],assets:a||[],artifacts:t||[],metrics:m})}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const logout=async()=>{await api('/api/auth/logout',{method:'POST'});setAuthenticated(false)};
 if(authenticated===null)return <div className="login-screen"><div className="loading"><span/>正在连接 ShopPilot…</div></div>;
 if(!authenticated)return <Login onSuccess={()=>{setAuthenticated(true);load()}}/>;
 const pending=runs.filter(r=>['waiting_review','pending_review','revision_required'].includes(r.status)).length;
 return <div className="shell"><aside><div className="brand"><span><Sparkles/></span><div><b>ShopPilot</b><small>AI Commerce OS</small></div></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}><Icon/>{label}{id==='campaigns'&&<em>{runs.length}</em>}</button>)}</nav><div className="aside-foot"><div className="runtime"><i className={runtime?.ready?'ok':''}/><div><b>{runtime?.runtime_mode==='agno'?'Agno 正式运行':'离线演示'}</b><small>{runtime?.model_id||'连接中…'}</small></div></div><button className="operator" onClick={logout}><span>OP</span><div><b>运营负责人</b><small>单管理员工作区</small></div><LogOut/></button></div></aside><main><header><div><small>{view==='run'?'CAMPAIGN WORKSPACE':view.toUpperCase()}</small><h1>{view==='run'?selected?.campaign.product:nav.find(n=>n[0]===view)?.[1]}</h1></div><div className="header-actions"><button className="icon" onClick={load}><RefreshCw/></button><button className="primary" onClick={()=>setView('create')}><Play/>新建 Campaign</button></div></header>{error&&<div className="alert"><TriangleAlert/>{error}</div>}{busy&&<div className="loading"><span/>正在同步运营数据…</div>}{!busy&&view==='dashboard'&&<Dashboard runs={runs} agents={agents} pending={pending} runtime={runtime} openRun={openRun}/>} {!busy&&view==='agents'&&<Agents agents={agents}/>} {!busy&&view==='capabilities'&&<Capabilities/>} {!busy&&view==='campaigns'&&<Campaigns runs={runs} openRun={openRun}/>} {!busy&&view==='create'&&<CreateCampaign onCreated={(r)=>{setRuns([r,...runs]);openRun(r)}}/>} {!busy&&view==='run'&&selected&&<RunWorkspace run={selected} stages={stages} bundle={bundle} reload={()=>openRun(selected)}/>} {!busy&&view==='assets'&&<AssetCatalog runs={runs}/>} {!busy&&view==='settings'&&<PlatformSettings runtime={runtime}/>}</main></div>
}

function Login({onSuccess}:{onSuccess:()=>void}){const[username,setUsername]=useState('admin'),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const submit=async(e:any)=>{e.preventDefault();setBusy(true);setError('');try{await api('/api/auth/login',{method:'POST',body:JSON.stringify({username,password})});onSuccess()}catch(e:any){setError(e.message)}finally{setBusy(false)}};return <div className="login-screen"><section className="login-brand"><div className="login-logo"><Sparkles/></div><span>SHOPILOT · AI COMMERCE OS</span><h1>把运营流程交给 Agent，<br/><em>把最终判断留给你。</em></h1><p>研究、策略、创意、合规与优化在一条受控工作流中运行。每个阶段可追踪、可审核、可沉淀为资产。</p><div className="login-points"><div><Bot/><span><b>Agent Fleet</b><small>统一配置 Skill、Tool 与 MCP</small></span></div><div><Network/><span><b>Trace Graph</b><small>查看每一步模型与工具调用</small></span></div><div><ShieldCheck/><span><b>Human Gate</b><small>审批后才会进入下一阶段</small></span></div></div></section><section className="login-form-wrap"><form className="login-form" onSubmit={submit}><small>OPERATIONS LOGIN</small><h2>登录运营工作台</h2><p>使用部署时设置的单一管理员账号。</p>{error&&<div className="login-error"><TriangleAlert/>{error}</div>}<label>管理员账号<input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username"/></label><label>密码<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" placeholder="输入管理员密码"/></label><button className="primary" disabled={busy}>{busy?'验证中…':'安全登录'}<ArrowRight/></button><div className="login-safe"><LockKeyhole/><span><b>Session protected</b><small>HttpOnly Cookie · CSRF · SameSite</small></span></div></form></section></div>}

function Dashboard({runs,agents,pending,runtime,openRun}:{runs:Run[];agents:Agent[];pending:number;runtime:any;openRun:(r:Run)=>void}){return <div className="content"><section className="hero"><div><span className="kicker"><Activity/>OPERATIONS CONTROL PLANE</span><h2>让每个 Agent 的决策<br/><em>可见、可审、可沉淀。</em></h2><p>从市场证据到创意资产，每个阶段必须经过你的审核，所有 Agent、工具调用和结果都留在同一条可追踪链路里。</p></div><div className="hero-orbit"><span className="core">SP<small>AGNO</small></span><span className="sat a">Research<small>Team · 5</small></span><span className="sat b">Creative<small>Agent</small></span><span className="sat c">Gate<small>Human</small></span></div></section><div className="stats"><Stat icon={Layers3} label="Campaign Runs" value={runs.length}/><Stat icon={LockKeyhole} label="待审核阶段" value={pending}/><Stat icon={Bot} label="Agent 成员" value={agents.length}/><Stat icon={ShieldCheck} label="运行状态" value={runtime?.ready?'READY':'CHECK'}/></div><div className="grid two"><section className="panel"><PanelTitle eyebrow="RECENT CAMPAIGNS" title="最近运行"/><div className="run-list">{runs.slice(0,5).map(r=><button key={r.run_id} onClick={()=>openRun(r)}><span className="product">{r.campaign.product?.slice(0,1)}</span><div><b>{r.campaign.product}</b><small>{r.campaign.brand} · {r.campaign.platform}</small></div><Badge value={r.status}/><ChevronRight/></button>)}{!runs.length&&<Empty title="还没有 Campaign" body="创建任务后，阶段进度与待审核事项会显示在这里。"/>}</div></section><section className="panel"><PanelTitle eyebrow="AGENT FLEET" title="能力状态"/><div className="agent-mini">{agents.slice(0,6).map(a=><div key={a.id}><span><Bot/></span><div><b>{a.name}</b><small>{a.tools.length} Tools · {a.mcp_servers.length} MCP</small></div><i/></div>)}</div></section></div></div>}
function Stat({icon:Icon,label,value}:any){return <div className="stat"><span><Icon/></span><div><small>{label}</small><b>{value}</b></div></div>}
function PanelTitle({eyebrow,title,extra}:{eyebrow:string;title:string;extra?:any}){return <div className="panel-title"><div><small>{eyebrow}</small><h3>{title}</h3></div>{extra}</div>}

function Agents({agents}:{agents:Agent[]}){const[current,setCurrent]=useState<Agent|undefined>(agents[0]);return <div className="content"><div className="split"><section className="panel roster"><PanelTitle eyebrow="AGENT REGISTRY" title={`${agents.length} 个 Agent`}/><label className="search"><Search/><input placeholder="搜索 Agent、角色或能力"/></label>{agents.map(a=><button key={a.id} className={current?.id===a.id?'selected':''} onClick={()=>setCurrent(a)}><span><Bot/></span><div><b>{a.name}</b><small>{a.role}</small></div><Badge value={a.status}/></button>)}</section><section className="panel agent-detail">{current?<><div className="agent-head"><span><Bot/></span><div><small>AGENT DEFINITION · {current.id}@{current.version}</small><h2>{current.name}</h2><p>{current.role}</p></div><Badge value={current.status}/></div><div className="meta-grid"><div><small>模型策略</small><b>{current.model_policy}</b></div><div><small>固定版本</small><b>v{current.version}</b></div><div><small>副作用策略</small><b>Default deny</b></div></div><CapabilityBlock title="Skills" icon={Sparkles} items={current.skills}/><CapabilityBlock title="Tools" icon={Wrench} items={current.tools}/><CapabilityBlock title="MCP Servers" icon={Network} items={current.mcp_servers}/><div className="notice"><ShieldCheck/><div><b>运行时能力固定</b><p>配置变更产生新版本；运行中的 Campaign 继续使用启动时快照。</p></div></div></>:<Empty title="没有 Agent" body="能力 Registry 尚未加载。"/>}</section></div></div>}
function CapabilityBlock({title,icon:Icon,items}:{title:string;icon:any;items:string[]}){return <section className="cap-block"><h4><Icon/>{title}<em>{items.length}</em></h4><div>{items.length?items.map(i=><span key={i}>{i}<Check/></span>):<small>未绑定任何 {title}</small>}</div></section>}

function Capabilities(){const[tabs,setTabs]=useState('tools'),[data,setData]=useState<Record<string,any[]>>({tools:[],skills:[],mcp:[]});useEffect(()=>{Promise.all([api('/api/tools'),api('/api/skills'),api('/api/mcp-servers')]).then(([a,b,c])=>setData({tools:a.items||[],skills:b.items||[],mcp:c.items||[]}))},[]);return <div className="content"><section className="panel"><PanelTitle eyebrow="CAPABILITY CATALOG" title="受治理的能力目录" extra={<span className="secure"><ShieldCheck/>默认拒绝</span>}/><div className="tabs">{[['tools','Tools'],['skills','Skills'],['mcp','MCP Servers']].map(([id,l])=><button className={tabs===id?'active':''} onClick={()=>setTabs(id)}>{l}<em>{data[id].length}</em></button>)}</div><div className="catalog">{data[tabs].map(item=><article key={item.id}><div className="catalog-icon">{tabs==='mcp'?<Network/>:tabs==='skills'?<Sparkles/>:<Wrench/>}</div><div><small>{item.id}@{item.version}</small><h3>{item.name||item.id}</h3><p>{item.description||item.function_name||item.transport}</p></div><div className="catalog-meta"><Badge value="ready"/>{item.side_effect&&<span>{item.side_effect}</span>}{item.timeout_seconds&&<span>{item.timeout_seconds}s timeout</span>}</div></article>)}{!data[tabs].length&&<Empty title="目录为空" body="当前 Registry 没有注册此类能力。"/>}</div></section></div>}

function CreateCampaign({onCreated}:{onCreated:(run:Run)=>void}){const[form,setForm]=useState({product:'',brand:'',target_audience:'',platform:'xiaohongshu',goal:'提升点击率',constraints:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');const submit=async(e:any)=>{e.preventDefault();setBusy(true);try{const run=await api<Run>('/api/runs',{method:'POST',body:JSON.stringify({...form,constraints:form.constraints.split('\n').map(x=>x.trim()).filter(Boolean)})});onCreated(run)}catch(e:any){setError(e.message)}finally{setBusy(false)}};return <div className="content"><div className="create-grid"><form className="panel create-form" onSubmit={submit}><span className="kicker">NEW CAMPAIGN · AGNO WORKFLOW</span><h2>创建一次可审核的运营任务</h2><p>提交后只执行市场调研；Research 审核通过后，后续阶段才会依次解锁。</p>{error&&<div className="alert"><TriangleAlert/>{error}</div>}<label>商品名称<input required value={form.product} onChange={e=>setForm({...form,product:e.target.value})}/></label><div className="form-row"><label>品牌<input required value={form.brand} onChange={e=>setForm({...form,brand:e.target.value})}/></label><label>目标平台<select value={form.platform} onChange={e=>setForm({...form,platform:e.target.value})}><option value="xiaohongshu">小红书</option><option value="douyin">抖音</option><option value="tmall">天猫</option><option value="jd">京东</option></select></label></div><label>目标人群<input required value={form.target_audience} onChange={e=>setForm({...form,target_audience:e.target.value})}/></label><label>营销目标<select value={form.goal} onChange={e=>setForm({...form,goal:e.target.value})}><option>提升点击率</option><option>促进转化</option><option>新品认知</option><option>种草收藏</option></select></label><label>品牌与合规约束<textarea rows={4} value={form.constraints} onChange={e=>setForm({...form,constraints:e.target.value})}/></label><button className="primary wide" disabled={busy}><Play/>{busy?'正在启动 Agno…':'启动阶段化 Workflow'}<ArrowRight/></button></form><aside className="panel create-guide"><PanelTitle eyebrow="CONTROLLED FLOW" title="阶段门禁"/><p><ShieldCheck/> 每一阶段都有 Agent、Trace、Evidence、Asset 和人工审核。</p><p><LockKeyhole/> 没有你的批准，下一阶段不会执行或发布。</p></aside></div></div>}
function Campaigns({runs,openRun}:{runs:Run[];openRun:(r:Run)=>void}){return <div className="content"><section className="panel"><PanelTitle eyebrow="CAMPAIGN RUNS" title="运营任务与阶段门禁" extra={<button className="primary"><Play/>创建 Campaign</button>}/><div className="campaign-table"><div className="thead"><span>Campaign</span><span>平台</span><span>Runtime</span><span>状态</span><span>更新时间</span><span/></div>{runs.map(r=><button key={r.run_id} onClick={()=>openRun(r)}><span><i>{r.campaign.product?.slice(0,1)}</i><b>{r.campaign.product}<small>{r.campaign.brand} · {r.run_id.slice(0,10)}</small></b></span><span>{r.campaign.platform}</span><span>{r.runtime_mode} / {r.model_id}</span><span><Badge value={r.status}/></span><span>{new Date(r.updated_at).toLocaleString('zh-CN')}</span><ChevronRight/></button>)}{!runs.length&&<Empty title="暂无 Campaign" body="创建一个真实商品运营任务开始工作流。"/>}</div></section></div>}

function RunWorkspace({run,stages,bundle,reload}:{run:Run;stages:Stage[];bundle:any;reload:()=>void}){const[current,setCurrent]=useState(stages.find(s=>s.status==='pending_review')?.stage_id||stages[1]?.stage_id);const stage=stages.find(s=>s.stage_id===current);const[tab,setTab]=useState('result');const review=async(decision:string)=>{const feedback=window.prompt(decision==='approve'?'审批备注（可选）':'请输入具体修改要求')||'';if(decision==='reject'&&!feedback)return;await api(`/api/runs/${run.run_id}/stages/${current}/${decision}`,{method:'POST',body:JSON.stringify({feedback})});reload()};return <div className="workspace"><aside className="stage-rail"><div><small>CAMPAIGN FLOW</small><b>{run.campaign.brand}</b><p>{run.run_id.slice(0,14)}</p></div>{stages.map((s,i)=><button key={s.stage_id} disabled={s.status==='locked'} className={`${current===s.stage_id?'active':''} ${s.status}`} onClick={()=>setCurrent(s.stage_id)}><span>{s.status==='approved'?<Check/>:s.status==='locked'?<LockKeyhole/>:String(i+1).padStart(2,'0')}</span><div><b>{s.name}</b><small>v{s.version} · {statusCN[s.status]}</small></div><ChevronRight/></button>)}</aside><section className="stage-main"><div className="stage-head"><div><span className="kicker">STAGE {String((stage?.sequence||0)+1).padStart(2,'0')}</span><h2>{stage?.name}</h2><p>查看 Agent 执行过程、证据、产出资产和审核历史。</p></div>{stage&&<Badge value={stage.status}/>}</div><div className="tabs"><button className={tab==='result'?'active':''} onClick={()=>setTab('result')}>生成结果</button><button className={tab==='trace'?'active':''} onClick={()=>setTab('trace')}>Trace 调用树</button><button className={tab==='evidence'?'active':''} onClick={()=>setTab('evidence')}>Evidence <em>{bundle.evidence?.length||0}</em></button><button className={tab==='assets'?'active':''} onClick={()=>setTab('assets')}>Assets <em>{bundle.assets?.length||0}</em></button></div><div className="stage-content">{tab==='result'&&<Results artifacts={bundle.artifacts}/>} {tab==='trace'&&<TraceTree stages={stages} spans={bundle.graph?.spans||[]} metrics={bundle.metrics}/>} {tab==='evidence'&&<Evidence items={bundle.evidence||[]} conflicts={bundle.conflicts||[]}/>} {tab==='assets'&&<Assets items={bundle.assets||[]}/>}</div></section><aside className="review-panel"><PanelTitle eyebrow="HUMAN GATE" title="阶段审核"/><div className="review-state"><span><ShieldCheck/></span><b>{stage?.status==='pending_review'?'等待你的判断':statusCN[stage?.status||'']}</b><p>审核与当前阶段 v{stage?.version} 绑定；新版本会使下游结果失效。</p></div><div className="review-checks"><p><Check/>已检查生成结果</p><p><Check/>已检查证据与引用</p><p><Check/>已检查资产和执行 Trace</p></div><button className="primary wide" disabled={stage?.status!=='pending_review'} onClick={()=>review('approve')}><Check/>批准进入下一阶段</button><button className="danger wide" disabled={!['pending_review','revision_required'].includes(stage?.status||'')} onClick={()=>review('reject')}><TriangleAlert/>驳回并创建新版本</button><small className="gate-note"><LockKeyhole/> 下一阶段在本阶段批准前保持锁定。</small></aside></div>}
function Results({artifacts}:{artifacts:any[]}){return <div className="cards">{artifacts?.map((a,i)=><article className="result-card" key={i}><div><FileText/><span>{a.kind}</span><Badge value="ready"/></div><pre>{JSON.stringify(a.data,null,2)}</pre></article>)}{!artifacts?.length&&<Empty title="暂无阶段结果" body="Agent 完成执行后，结构化 Artifact 会显示在这里。"/>}</div>}
function TraceTree({stages,spans,metrics}:{stages:Stage[];spans:any[];metrics:any}){return <div><div className="trace-metrics"><Stat icon={Activity} label="Spans" value={metrics?.span_count||spans.length}/><Stat icon={Gauge} label="平均时延" value={`${Math.round(metrics?.average_latency_ms||0)}ms`}/><Stat icon={BarChart3} label="Tokens" value={metrics?.total_tokens||0}/></div><div className="trace-tree"><div className="trace-node root"><Activity/><b>Campaign Run</b><small>{stages.length} stages</small></div>{stages.map(s=><div className="trace-branch" key={s.stage_id}><span/><div className="trace-node"><Layers3/><b>Stage · {s.name}</b><Badge value={s.status}/></div>{spans.filter(x=>x.attributes?.stage===s.stage_id||x.name?.toLowerCase().includes(s.stage_id)).map((x:any)=><div className="trace-node child" key={x.span_id}><Bot/><b>{x.kind} · {x.name}</b><small>{x.duration_ms||0}ms</small></div>)}</div>)}</div></div>}
function Evidence({items,conflicts}:{items:any[];conflicts:any[]}){return <div><div className="evidence-summary"><div><b>{items.length}</b><small>规范化证据</small></div><div><b>{conflicts.length}</b><small>未解决冲突</small></div><div><b>{items.length?Math.round(items.filter(x=>x.confidence>=.7).length/items.length*100):0}%</b><small>高置信覆盖</small></div></div>{conflicts.map(c=><div className="conflict"><TriangleAlert/><div><b>{c.subject}</b><p>{c.description}</p></div><Badge value={c.resolution_status}/></div>)}<div className="evidence-list">{items.map(e=><article key={e.evidence_id}><span><Globe2/></span><div><small>{e.source_title||new URL(e.source_url).hostname} · {Math.round(e.confidence*100)}%</small><h4>{e.claim}</h4><p>{e.excerpt}</p><a href={e.source_url} target="_blank" rel="noreferrer">查看原始来源 <ArrowRight/></a></div>{e.prompt_injection_suspected&&<Badge value="quarantined"/>}</article>)}</div>{!items.length&&<Empty title="暂无外部证据" body="Research Team 采集并经过 Evidence Reviewer 规范化后显示。"/>}</div>}
function Assets({items}:{items:any[]}){return <div className="asset-grid">{items.map(a=><article key={`${a.asset_id}-${a.version}`}><div className="asset-preview"><FileText/></div><div><small>{a.kind} · v{a.version}</small><h4>{a.filename}</h4><p>{a.mime_type} · {(a.size_bytes/1024).toFixed(1)} KB</p><span>SHA-256 {a.sha256.slice(0,12)}…</span><a href={`/api/assets/${a.asset_id}/versions/${a.version}/download`}>下载资产 <ArrowRight/></a></div></article>)}{!items.length&&<Empty title="暂无资产" body="研究报告、创意、广告文本和图片会作为版本化资产保存在这里。"/>}</div>}
function AssetCatalog({runs}:{runs:Run[]}){return <div className="content"><section className="panel"><PanelTitle eyebrow="ASSET CATALOG" title="版本化运营资产"/><Empty title="从 Campaign 进入资产" body={`当前有 ${runs.length} 个 Campaign。打开运行详情即可预览、下载并查看资产血缘。`}/></section></div>}
function PlatformSettings({runtime}:{runtime:any}){return <div className="content"><div className="grid two"><section className="panel"><PanelTitle eyebrow="RUNTIME" title="Agno 模型运行时"/><div className="settings-list">{Object.entries(runtime||{}).filter(([k])=>!k.includes('key')).map(([k,v])=><div><span>{k}</span><b>{String(v)}</b></div>)}</div></section><section className="panel"><PanelTitle eyebrow="INFRASTRUCTURE" title="平台基础服务"/><div className="infra-list"><p><Database/><span><b>PostgreSQL</b><small>Canonical business records</small></span><Badge value="ready"/></p><p><Activity/><span><b>Redis</b><small>Jobs · locks · live events</small></span><Badge value="ready"/></p><p><Archive/><span><b>MinIO / S3</b><small>Immutable asset objects</small></span><Badge value="ready"/></p></div></section></div></div>}


